from enum import Enum

class ResponseSignal(Enum):
    
    FILE_VALIDATE_SUCCESS="FILE VALIDATE SUCCESS"
    FILE_TYPE_NOT_SUPPORTED="FILE NOT SUPPORTED"
    FILE_SIZE_EXCEEDED="FILE IS LARGE"
    FILE_UPLOAD_SUCCESS="FILE UPLOAD SUCCESS"
    FILE_UPLOAD_FAILED="FILE UPLOAD FAILED"
    
    
    